title: "Rashmi Mahadevaiah's Portfolio"
description: "AI Product Manager with expertise in IoT, Machine Learning, and Analytics"
baseurl: ""
url: "https://rashmimahadevaiah.github.io"

# Theme settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - .gitignore
  - package.json
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src/js
  - src/fonts
permalink: pretty
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
  sass_dir: src/css
  css_dir: src/css
  images_dir: src/assets/images
  javascripts_dir: src/assets/js
  fonts_dir: src/assets/fonts